// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQEekRbIeePnUO7iZwvXoJ4emR3iV5FI4',
    appId: '1:1033275894064:web:aebd715910e595962840f5',
    messagingSenderId: '1033275894064',
    projectId: 'final-project-2a0d9',
    authDomain: 'final-project-2a0d9.firebaseapp.com',
    storageBucket: 'final-project-2a0d9.appspot.com',
    measurementId: 'G-H44JFTYYD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_wMgBoFkQKTHsjnt8NXX0rCsuYalDaU8',
    appId: '1:1033275894064:android:cc9b8ca06db77a102840f5',
    messagingSenderId: '1033275894064',
    projectId: 'final-project-2a0d9',
    storageBucket: 'final-project-2a0d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJtU04GpufO0n598Es_SwyLYRkRW3GEg',
    appId: '1:1033275894064:ios:4d2401c260abead02840f5',
    messagingSenderId: '1033275894064',
    projectId: 'final-project-2a0d9',
    storageBucket: 'final-project-2a0d9.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQEekRbIeePnUO7iZwvXoJ4emR3iV5FI4',
    appId: '1:1033275894064:web:183837f9f377020c2840f5',
    messagingSenderId: '1033275894064',
    projectId: 'final-project-2a0d9',
    authDomain: 'final-project-2a0d9.firebaseapp.com',
    storageBucket: 'final-project-2a0d9.appspot.com',
    measurementId: 'G-BWWZWE211F',
  );
}
